# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002b3c8170815a0da6abe48b39dae019ee755462d8ef4bb251f88a070867e06a49e2655489a4f5a0b937d06ffef8bafa661abcc61c71e0f53afe00e048cbaf4e

test:
  secret_key_base: 666d5d9b9cc0f744f0663f5b657e080d267a5b14d7bcd56c66c4efdf341beee41c5191d28ab2d423784fc56372654942507fd72846f6af8d03620bc2f3ffabe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
